#!/usr/bin/env python3
"""Two-digit page numbers ("P.12") for the All Magic and GF Abilities parts.

The menus' "P.n" page header is drawn by 0x4C0370(ctx, prim, x, y, colour, page):
it formats page+1 into five digit sprites (0x28 + digit, via 0x4B87F0), blanks the tens
digit, then draws the "P." sprite (0x32) and only the units digit 9 px to its right. So
page 12 shows "P.2". The game also has a two-digit version, 0x4C02F0, with the same
arguments, which draws the tens digit at +9 and the units at +15.

This rewrites 0x4C0370 in place, with no code cave: pages 10+ jump to 0x4C02F0, and pages
1-9 draw exactly what vanilla draws. Dropping the tens-blanking call (whose result the
one-digit path never drew) makes room for the page test.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ff8hext import Hext, Image, asm, default_exe  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "FF8Unlimited", "options", "PageNumbers")
FUNC = 0x4C0370
END = 0x4C03E0              # next function (0x4C03E0); 0x4C03D7.. is int3/nop padding
TWO_DIGIT = 0x4C02F0
ITOA = 0x4B87F0             # (value, out, first_sprite)
DRAW = 0x4B7210             # (ctx, prim, sprite, x, y, colour) -> next prim

SOURCE = """
mov ecx, dword ptr [esp + 0x18]
cmp ecx, 9
jae 0x{two:X}
sub esp, 0x10
lea eax, [esp]
inc ecx
push ebx
push ebp
push esi
push edi
push 0x28
push eax
push ecx
call 0x{itoa:X}
mov esi, dword ptr [esp + 0x40]
mov edi, dword ptr [esp + 0x3c]
mov ebx, dword ptr [esp + 0x38]
mov eax, dword ptr [esp + 0x34]
mov ebp, dword ptr [esp + 0x30]
push esi
push edi
push ebx
push 0x32
push eax
push ebp
call 0x{draw:X}
movsx ecx, byte ptr [esp + 0x38]
push esi
add ebx, 9
push edi
push ebx
push ecx
push eax
push ebp
call 0x{draw:X}
add esp, 0x3c
pop edi
pop esi
pop ebp
pop ebx
add esp, 0x10
ret
""".format(two=TWO_DIGIT, itoa=ITOA, draw=DRAW)

# first bytes of the vanilla function, checked before patching
EXPECT = bytes.fromhex("8b4c241883ec108d4424004153555657")


def build(exe=None):
    img = Image(exe or default_exe())
    have = img.read(FUNC, len(EXPECT))
    if have != EXPECT:
        raise SystemExit("unexpected bytes at %08X: %s" % (FUNC, have.hex()))
    code = asm(SOURCE, FUNC)
    if FUNC + len(code) > END:
        raise SystemExit("rewrite is %d bytes, only %d fit" % (len(code), END - FUNC))
    code += b"\xcc" * (0x4C03D7 - FUNC - len(code)) if FUNC + len(code) < 0x4C03D7 else b""
    h = Hext("FF8 Unlimited - two-digit page numbers (FF8 Steam 2013, FF8_EN.exe)")
    h.comment("Generated by tools/build_page_numbers.py - edit that, not this file.")
    h.blank()
    h.write(FUNC, code, "page header P.n: pages 10+ use the two-digit header 0x%X" % TWO_DIGIT)
    h.save(os.path.join(ROOT, "hext", "page_numbers.hext"))
    return code


if __name__ == "__main__":
    code = build(sys.argv[1] if len(sys.argv) > 1 else None)
    print("built %s: %d bytes rewritten at %08X" % (os.path.normpath(ROOT), len(code), FUNC))
